[tool.poetry]
name = "cd-py-date-funcs"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
cd-py-consts = {git = "https://github.com/RulezKT/cd_py_consts.git"}

